### DISCUSSION TITLE
Error when checking the capability of gRPC package with RA-TLS

### DISCUSSION THREAD

**Discussion by blank-vax** [occlum/occlum#1260] [General]
Following the instructions in the `README.md` file in `occlum/tools/toolchains/grpc_ratls/ra_tls/`, the commands `./download_and_prepare.sh`, `./build_and_install.sh` and `./build_occlum_instance.sh` are performed step by step. However, when executing the command `./run.sh server` , the following error occurs:
```
Error: Os { code : 2, kind : NotFound, message: "No such file or directory" }
```
During the build of these two occlum instances, we set:
```
bomfile="../grpc_ratls_server.yaml"
bomfile="../grpc_ratls_client_yaml"
copy_bom -f $bomfile --root image --include-dir /opt/occlum/etc/template
```
While the `grpc_ratls_client.yaml` and the `grpc_ratls_server.yaml` are set as follows separately:
```
targets:
  - target: /bin/
    copy:
      - files:
        - ../grpc-src/examples/cpp/ratls/build/client
```
```
targets:
  - target: /bin/
    copy:
      - files:
        - ../grpc-src/examples/cpp/ratls/build/server
```
Also, I check the two occlum instances `occlum_client` and `occlum_server`, the executable file `client` and `server` are located in the `image/bin/` directory separately. So I wonder why when the `occlum run /bin/server` command is running, the error occurs.
