### ISSUE TITLE
[RFC] Modify Occlum config file for EDMM support

### ISSUE THREAD

**Issue by jessehui** [occlum/occlum#1069]
# For Occlum v1.0 (current NGO)
## Summary
[summary]: #summary

Occlum 1.0 is on its way. And we have changed the user configuration file format from `JSON` to `YAML`. EDMM support is still under development and may not come together with Occlum 1.0. However, we would like to consider for future EDMM support to work with the new `YAML` user configuration file. 

## Guide-level explanation
The latest configuration file template can be found at: https://github.com/occlum/ngo/blob/master/etc/template/Occlum.yaml

The main modifications include the vcpu number and the memory configuration fields listed below:

```yaml
# All the settings below can only take effect after `occlum build`.
resource_limits:
  # The heap size of LibOS kernel
  kernel_space_heap_size: 32MB
  # The stack size of LibOS kernel. If not sure, don't modify it.
  kernel_space_stack_size: 1MB
  # The total size of enclave memory available to LibOS processes.
  # This size should be adjusted per different applications.
  # If reports ENOMEM error, try increase this size.
  user_space_size: 256MB
  # The minimum and maximum OS threads used by LibOS. If not sure, don't modify them.
  min_num_of_cpus: 1
  max_num_of_cpus: 128
process:
  # Default stack size for each process. If not sure, don't modify it.
  default_stack_size: 4MB
  # Default heap size for each process. If not sure, don't modify it.
  default_heap_size: 32MB
```

The main purpose of this modification is to decrease the time and effort that users need to modify the numbers to get the applications to run. The main goals are:
1. The default template can be used most of the time.
2. Don't pay for the trim cost (make init equal to min)
3. Hide the details that users need not know

New config file:
```yaml
# All the settings below can only take effect after `occlum build`.
resource_limits:
  # The number of OS threads created for this instance.
  num_of_cpus: 128
  # The stack size of LibOS kernel.
  kernel_space_stack_size: 16MB
  # The heap size of LibOS kernel.
  kernel_space_heap_size:
    # Reserved and committed during the initialization stage. The more, the longer it takes to initialize.
    init: 32MB
    # Only committed when necessary. If memory insufficiency occurs, increase this field.
    max:  512MB
  # The total size of enclave memory available to the user applications running in LibOS.
  user_space_memory_size:
    # Reserved and committed during the initialization stage. The more, the longer it takes to initialize.
    init: 256MB
    # Only committed when necessary. If memory insufficiency occurs, increase this field.
    max:  64GB


# Default memory size for the users' processes. If not sure, don't modify it.
process:
  # Default stack size for each process.
  default_stack_size: 4MB
  # Default heap size for each process.
  default_heap_size: 32MB
```

## Reference-level explanation
[reference-level-explanation]: #reference-level-explanation

For kernel heap memory fields, there are two sub-fields which are `init` and `max`. The fields are corresponding to specific fields in `Enclave.xml`.
heap init size -> HeapInitSize, HeapMinSize
heap max size -> HeapMaxSize

For kernel stack fields, since we won't use a huge number of TCSs, we just use stack max size for kernel stack.
kernel stack size -> StackMinSize, StackMaxSize

For user space memory, the max_size corresponds to the `UserRegionSize` which is newly introduced to work together with EDMM. However, for init_size, there is no corresponding field. We can do it in Occlum by committing the init size of memory during user space initialization. Or we can use reserved memory for init size and user region for max size. No matter what we do, we can keep the fields here for future possibilities.

For CPU number, use num_of_cpus as the init TCS number (plus TCS used by Occlum kernel). For max TCS number, we can hardcode a very big number in our source code.
num_of_cpus -> TCSMinPool, TCSNum
hard code a big number in source code -> TCSMaxPool

For the process field, there is no change.

# For Legacy Occlum (current Occlum)
## Summary
In the near future, the legacy Occlum will keep for a while. If the user uses Occlum on a platform with EDMM support, it would be better for us to leverage this feature as much as possible.

## Guide-level explanation

```JSON
    "resource_limits": {
        "kernel_space_heap_size": "32MB",
	    "kernel_space_heap_max_size": "1GB", -> NEW field, OPTIONAL
        "kernel_space_stack_size": "1MB", -> same as Occlum 1.0, equals to StackMinSize and StackMaxSize
        "user_space_size": "300MB",
        "max_num_of_threads": 32 -> actual init and min TCS number, max number hardcode in src code
    },
    "process": {
        "default_stack_size": "4MB",
        "default_heap_size": "32MB",
        "default_mmap_size": "100MB"
    },
```

Considering compatibility, use the same config file with one new OPTIONAL field `kernel_space_heap_max_size`.

If the user specifies this field, we use it directly as HeapMaxSize. If not, we put a big value to HeapMaxSize when generating `Enclave.xml`. HeapMinSize and HeapInitSize will use the value from `kernel_space_heap_size`.

For `kernel_space_stack_size` and `max_num_of_threads`, they are similar to the operation in Occlum 1.0 mentioned above. The `max_number_of_threads` value is not really what it means. But for compatibility, we just go this way.

Since the user space is managed by Occlum kernel with reserved memory API and will need a lot of work to leverage EDMM feature, the `user_space_size` field will keep it there and will NOT be dynamically managed.
