### ISSUE TITLE
ERROR:Segmentation fault - trying to run mongodb docker image with occlum

### ISSUE THREAD

**Issue by Dadoias** [occlum/occlum#1276]
I want to run MongoDB with Occlum starting by the docker mongoDB.

## Details 

- **Image:** mongo:4.4
- I'm using the repository occlum/example (https://github.com/occlum/occlum/tree/master/example).
- These are the modification in the script _'build_content.sh'_:
```
      export image="mongo"
      export image_tag="4.4"

      ...
      function build_tf_serving()
      {
          # Dump the application container rootfs content
          ./dump_rootfs.sh -i ${image} -d ${TF_DIR} -g ${image_tag}
      }
      ...
```
-I have included in the configuration YAML file all the libraries that MongoDB seems to use in the container, as well as all the MongoDB binaries (although I'm not certain if all of them are essential). Here is my YAML file:
```
includes:
  - base.yaml
targets:
  - target: /bin
    copy:
      - files:
        - ${TF_DIR}/rootfs/bin/mongod
        - ${TF_DIR}/rootfs/bin/mongo
        - ${TF_DIR}/rootfs/bin/mongodump
        - ${TF_DIR}/rootfs/bin/mongoexport
        - ${TF_DIR}/rootfs/bin/mongofiles
        - ${TF_DIR}/rootfs/bin/mongoimport
        - ${TF_DIR}/rootfs/bin/mongorestore
        - ${TF_DIR}/rootfs/bin/mongos
        - ${TF_DIR}/rootfs/bin/mongostat
        - ${TF_DIR}/rootfs/bin/mongotop
  - target: /opt/occlum/glibc/lib
    copy:
      - files:
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libcurl.so.4
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libresolv.so.2
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libcrypto.so.1.1
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libssl.so.1.1
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libdl.so.2
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/librt.so.1
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libm.so.6
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libgcc_s.so.1
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libpthread.so.0
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libc.so.6
        - ${TF_DIR}/rootfs/lib64/ld-linux-x86-64.so.2
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libnghttp2.so.14
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libidn2.so.0
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/librtmp.so.1
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libssh.so.4
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libpsl.so.5
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libgssapi_krb5.so.2
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libldap_r-2.4.so.2
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/liblber-2.4.so.2
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libbrotlidec.so.1
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libz.so.1
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libunistring.so.2
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libgnutls.so.30
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libhogweed.so.5
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libnettle.so.7
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libgmp.so.10
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libkrb5.so.3
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libk5crypto.so.3
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libcom_err.so.2
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libkrb5support.so.0
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libsasl2.so.2
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libgssapi.so.3
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libbrotlicommon.so.1
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libp11-kit.so.0
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libtasn1.so.6
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libkeyutils.so.1
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libheimntlm.so.0
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libkrb5.so.26
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libasn1.so.8
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libhcrypto.so.4
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libroken.so.18
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libffi.so.7
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libwind.so.0
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libheimbase.so.1
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libhx509.so.5
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libsqlite3.so.0
        - ${TF_DIR}/rootfs/lib/x86_64-linux-gnu/libcrypt.so.1
```

- After succesfully build the content and the images, I run mongoDB like this:

```
docker run --network=host \
        --device=/dev/sgx/enclave --device=/dev/sgx/provision \
        -v mongoData:/data/db \
        ${registry}/occlum_app:${tag} \
        taskset -c 0,1 occlum run /bin/mongod
```

## ERROR
this is the error log:
```
/opt/occlum/build/bin/occlum: line 354:    27 Segmentation fault      (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
```

Could you help me with this error?
Or, on the other hand, could you advise me on integrating MongoDB with Occlum
and suggest any necessary changes to the YAML configuration file?
