### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by saisai321123** [occlum/occlum#1379]
Do you know how to modify the time zone in Occlum

**Comment by qzheng527** [comment]
Put below in the bom file and rebuild (including copy_bom) the occlum instance.

- For glibc application:
```
  - target: /opt/occlum/glibc/etc
    copy:
      - files:
        - name: /usr/share/zoneinfo/Asia/Shanghai
          rename: localtime
```
- For musl-lib application:
```
  - target: /etc
    copy:
      - files:
        - name: /usr/share/zoneinfo/Asia/Shanghai
          rename: localtime
 ```

Above two could be verified by demo [bash](https://github.com/occlum/occlum/tree/master/demos/bash).
After adding above parts, try below command to make sure the timezone is as expected.
```
occlum run /bin/busybox date
```
