### ISSUE TITLE
[BUG]error running python demo

### ISSUE THREAD

**Issue by jcsora** [occlum/occlum#679]
# Describe the bug
Error running python_glibc demo in docker container.

# To reproduce
1. docker-compose exec occlum bash
2. cd demos/python/python_glibc
3. ./install_python_with_conda.sh
4. ./run_python_on_occlum.sh

# Expected behavior
Successfully run demo.

# Logs
```
root@e89696dcb99b:~/demos/python/python_glibc# ./run_python_on_occlum.sh
Enclave sign-tool: /opt/occlum/sgxsdk-tools/bin/x64/sgx_sign
Enclave sign-key: /opt/occlum/etc/template/Enclave.pem
SGX mode: HW
Building new image...
[+] Home dir is /root
[+] Open token file success!
[+] Token file valid!
[+] Init Enclave Successful 15126874816514!
Generate the SEFS image successfully
Building the initfs...
[+] Home dir is /root
[+] Open token file success!
[+] Token file valid!
[+] Init Enclave Successful 15199889260546!
Generate the SEFS image successfully
Building libOS...
Signing the enclave...
<EnclaveConfiguration>
    <ProdID>0</ProdID>
    <ISVSVN>0</ISVSVN>
    <StackMaxSize>1048576</StackMaxSize>
    <StackMinSize>1048576</StackMinSize>
    <HeapMaxSize>268435456</HeapMaxSize>
    <HeapMinSize>268435456</HeapMinSize>
    <TCSNum>32</TCSNum>
    <TCSPolicy>1</TCSPolicy>
    <DisableDebug>0</DisableDebug>
    <MiscSelect>0</MiscSelect>
    <MiscMask>0xFFFFFFFF</MiscMask>
    <ReservedMemMaxSize>671088640</ReservedMemMaxSize>
    <ReservedMemMinSize>671088640</ReservedMemMinSize>
    <ReservedMemInitSize>671088640</ReservedMemInitSize>
    <ReservedMemExecutable>1</ReservedMemExecutable>
</EnclaveConfiguration>
tcs_num 32, tcs_max_num 32, tcs_min_pool 1
The required memory is 976248832B.
The required memory is 0x3a306000, 953368 KB.
Succeed.
Built the Occlum image and enclave successfully
occlum run /bin/python3 demo.py
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /root/occlum/deps/sefs/rcore-fs-unionfs/src/lib.rs:491:18
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
note: Some details are omitted, call backtrace::enable_backtrace() with 'PrintFormat::Full' for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
/opt/occlum/build/bin/occlum: line 315:  3581 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
```

# Environment

- HW: SGX2
- OS: Ubuntu 20.04.3 LTS
- Kernel version: 5.14.0-051400-generic
- Docker image: occlum/occlum:0.24.1-ubuntu18.04
- Occlum version: 0.24.1

# Additional context
- docker-compose.yml:
```
version: "3.8"

services:
  occlum:
    image: occlum/occlum:0.24.1-ubuntu18.04
    #image: jcsora/occlum:latest
    devices:
      # For old IAS driver (not DCAP aware):
      #- /dev/isgx:/dev/isgx

      # For DCAP driver since v1.41 or in-tree kernel driver:
      - /dev/sgx/enclave:/dev/sgx/enclave
      - /dev/sgx/provision:/dev/sgx/provision
    tty: true
    networks:
      - occlum
```
