### ISSUE TITLE
[BUG] Suspect memory leak on Occlum FS

### ISSUE THREAD

**Issue by qzheng527** [occlum/occlum#680]
# Describe the bug
Once doing a long loop FS operation, the Occlum eventually will panic with below log:
```
memory allocation of 1377080 bytes failed/opt/occlum/build/bin/occlum: line 315: 680317 Illegal instruction     (core dumped) RUST_BACKTRACE=1 "$instance_dir/build/bin/occlum-run" "$@"
```
Increase the `kernel_space_heap_size` may delay the issue but can't fix it.

# To reproduce
Using the script below could reproduce the issue.
```
#!/bin/bash

loops=${1:-10000}

echo "loop $loops starts ..."

for i in $(seq 1 $loops)
do
    cat /proc/self/stat;
done

echo "loop ends"
```

BOM file for referene.
```
includes:
  - base.yaml
# bash
targets:
  # copy bash, busybox and test script
  - target: /bin
    copy:
      - files:
        - /opt/occlum/toolchains/bash/glibc/bash
        - ../busybox
        - ../test.sh
  - target: /bin
    # build a symlink: ln -s $linksrc $target/linkname
    createlinks:
      - src: /bin/bash
        linkname: sh
      - src: /bin/busybox
        linkname: cat
      - src: /bin/busybox
        linkname: sed
      - src: /bin/busybox
        linkname: echo
```

`Occlum run /bin/test.sh` will trigger the panic.

# Expected behavior
No panic happen.

# Environment

- HW: SGX1, SGX2
- OS: Ubuntu18.04
- Occlum version: 0.24.1
